fix clang compilation warning (interactive function missing)
drive-sdk/examples/vehicle-tool/vehicle_tool.c:159:2: warning: implicit declaration of function 'interactive' is invalid in C99 [-Wimplicit-function-declaration]
        interactive(opt_src, opt_dst, opt_dst_type, opt_psm);

by declaring the interactive function in vehicle_tool.c